### PR TITLE
Added missing browser hook

### PR DESCRIPTION
**Pull request by julianpoy**
This fixes the browser platform bug mentioned by many users.

### CODE REVIEW

**Comment by torch2424** [comment]
can you add the grunt concurrent in this as well? Or will that be a seperate branch?

**Comment by torch2424** [comment]
@julianpoy I forgot what you said if grunt concurrent was gonna be in this

**Comment by julianpoy** [comment]
Grunt concurrent should not be a problem anymore. It is not, however, included in this branch.

**Comment by torch2424** [comment]
Okay, well I shall pull in and we shall see!

**Comment by torch2424** [comment]
:hamburger: :smile:

**Pull request merged**
